### PR TITLE
fix: Fix type file generation to export types instead of declarations

### LINKED ISSUE #119: Fix type files geneartion to export only types
## 🐛 Bug Report

The type definition files output assignment which is not legal in definitions files. TypeScript definition files (`*.d.ts`) only declare types and do not assign values. It is a subtle difference, but the `=` should be changed to `:` and the `as const` removed.

### Expected Behavior

```ts
// es6/system/index.d.ts
export declare const color: {
  bg: {
    "default": "--cnvs-sys-color-bg-default",
    // ...
  },
  // ...
};

// es6/base/index.d.ts
export declare const cinnamon100: "--cnvs-base-palette-cinnamon-100";
```

### Actual Behavior

```ts
// es6/system/index.d.ts
export declare const color = {
  bg: {
    "default": "--cnvs-sys-color-bg-default",
    // ...
  } as const,
  // ...
} as const;

// es6/base/index.d.ts
export declare const cinnamon100 = "--cnvs-base-palette-cinnamon-100";
```

### PR DESCRIPTION
**Pull request by RayRedGoose**
## Issue

Fixes #119 

## Summary

PR contains a fix for type issue for users don't use `--skipLibCheck`.

## Release Category

Web Tokens

### Release Note

Type generation has been updated to fix a type issue happening for user who doesn't use `--skipLibCheck`. Now generated type files contains types (`export declare const cinnamon100: "--cnvs-base-palette-cinnamon-100";`) instead of value declarations (`export declare const cinnamon100 = "--cnvs-base-palette-cinnamon-100" as const;`). 

---

### CODE REVIEW

File: packages/canvas-tokens-docs/stories/brand/examples/Color.tsx [hunk 1]
```diff
@@ -15,6 +15,8 @@ const palettes = Object.keys(brand).map(key => {
   };
 });
 
+brand.alert.accent
+
```
Comment (RayRedGoose) [inline packages/canvas-tokens-docs/stories/brand/examples/Color.tsx:19]:
```suggestion
```

Comment (RayRedGoose) [inline packages/canvas-tokens-docs/stories/brand/examples/Color.tsx:19]:
```suggestion

```

**Review by NicholasBoll — APPROVED** [review]
